
# Configuration for the user
api_url: "https://api.marketrouter.ai"
deposit_amount: 0.2

# Configuration file for the Market Neutral Strategy System
model: "gpt-4o-mini"
temperature: 0.9
max_tokens: 16384
messages: [{"role": "user", "content": "First message from market neutral strategy to test the system."}]
background: "Given a collection of news articles focused on a specific sector of the S&P 500, the system should process the information to generate investment actions (BUY, HOLD, SELL) for each stock within the sector."
max_credit_per_instance: 0.02
percentage_reward: 1
instance_timeout: 65
gen_reward_timeout: 36000
gen_reward: 0.02

